### ISSUE TITLE
Websocket Crash

### ISSUE THREAD

**Issue by matejdro** [Chimerapps/niddler#26]
This just happened to me and it crashed the whole app:

```
FATAL EXCEPTION: OkHttp Dispatcher
    org.java_websocket.exceptions.WebsocketNotConnectedException
        at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:628)
        at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:605)
        at com.chimerapps.niddler.core.ServerConnection.send(ServerConnection.java:63)
        at com.chimerapps.niddler.core.NiddlerServer.sendToAll(NiddlerServer.java:202)
        at com.chimerapps.niddler.core.NiddlerImpl.send(NiddlerImpl.java:108)
        at com.chimerapps.niddler.core.Niddler.logResponse(Niddler.java:64)
        at com.chimerapps.niddler.interceptor.okhttp.NiddlerOkHttpInterceptor.intercept(NiddlerOkHttpInterceptor.java:217)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

Niddler 1.5.3. I can't reproduce anymore.

**Comment by NicolaVerbeeck** [comment]
Release 1.5.4 is being released with a fix that will prevent crashes
